travis:
  secure:
    BINSTAR_TOKEN: IsA4FE2J8GDruObqFhatCT6BO8+UQ4pzERU/w7dk7OOw/uTr/G5Dmp6RSul4kuKvdjOWf83LVfFpdEIZBmIJK1VbGuQim2Y4OAhn+uBTOrg+LQy6WOcL7T/MPecV6QF1ZxdlbsHvF32YWrXWOh4LUWOsJQXjROi00ugIGWof99WRKm0dGGJEsYOvdrhbtIIuKzT+lAUgTxXQuH1bqpIiyY98hZNBnv76jbPyR/VLLF6qJvNuRdDs3kZp2iYKlv6k5STaVFe8Jur2s0lRzvnv3/h1WJVzhCqbdjxhwz5Hgnq8VoS1TXBfndTiLeg38a3/pEirhQEznuYzJFnGi9gWNGB/+RqInBCI8vsDZdVh6kBB8pq2h1wqTgSsFWLJFhsluYfyF5waPRJWjwwB4TUrKZGQWFXzg/YDEmpXpQxQn8Je1Hu4dLF8vH3ckAKXVpA89krQW5SNgOswwIHsFHQ95r16Ufm1SBqcCt5x2aVxVc1FtB5I7DnuLcVlI2qYZb/y6snU8On6yU/j3bgocgHJS9YZJ/puGVrnnNFRW8qhVJMZlKwAdUcw2uskPE3XNmE5NHEAU/xfpcY7X+w67rXdmjgAyYc5mg6RCDNDcqG+P+ijPzv1wQ8h9MwUVMm46g279bxB8P34LDhLBix5MoBjID+IreqyYgl4CrE7VKOx6U0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
